input {
  file {
    path => "/var/log/app/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  # json {
  #   source => "message"
  # }
  mutate {
    rename => { "msg" => "message" }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "ft_transcendence-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
